# Generated by Django 4.1.3 on 2022-11-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cost_remove_cart_cost_remove_cart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
