# Generated by Django 4.1.3 on 2022-11-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_cost_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
