# Generated by Django 4.1.3 on 2022-11-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cost',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.CharField(default=10, max_length=100),
        ),
    ]
