# Generated by Django 4.1.3 on 2022-11-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_cart_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(default=0, max_length=100)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
