# Generated by Django 4.1.3 on 2022-11-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_cost_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
