# Generated by Django 4.1.3 on 2022-11-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_delete_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
