# Generated by Django 4.1.3 on 2022-11-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_coupen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupen',
        ),
    ]
